name: Bug Report
description: Report a reproducible bug or issue.
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the information below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a concise description of the bug.
      placeholder: The system crashes when...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Detailed explanation of the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe '...'
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: The drone should...
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: The drone did...
    validations:
      required: true

  - id: system_configuration
    type: textarea
    attributes:
      label: System configuration (software/hardware version, etc.)
    validations:
      required: true

  - type: textarea
    id: extra_and_attachments
    attributes:
      label: Additional details and attachments
      description: Include screenshots, logs, or other relevant files.
