name: Feature Request
description: Suggest an enhancement or new feature.
title: "[Feature]: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide the details below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly summarize the feature request.
      placeholder: Add support for...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Explain the feature and how it would benefit users.
      placeholder: Detailed explanation...
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Describe why this feature should be added.
      placeholder: This feature would allow users to...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define how to measure the success of this feature.
      placeholder: |
        - The system allows...
        - Users can...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots.
      placeholder: Related issues, suggestions...
    validations:
      required: false
